export * from './home'
export * from './eventos'
export * from './general/BannerSection'
export * from './general/InfoSectionSplit'
export * from './general/GallerySection'
export * from './general/InstitutionSection'
